@startuml
package ucf.assignments
{
    Class Task
    {
        String title
        String description
        String dueDate
        Boolean complete
    }

    Class App
    {
        Start
        Main
    }

    Class GUIController
    {
        void addTask
        void clearAllTasks
        void deleteTask
        void markAsDone
        void saveToCSV
        void loadFile
        void shutdown
        void updateTask
        void viewAll
        void viewComplete
        void viewIncomplete
        void initialize
    }
}
@enduml